# Generated by Django 4.2.16 on 2026-04-14 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('platform', models.CharField(choices=[('zalo', 'Zalo OA'), ('facebook', 'Facebook Messenger')], max_length=20)),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('webhook_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kênh',
                'verbose_name_plural': 'Kênh',
                'db_table': 'channels',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=255)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Đang mở'), ('closed', 'Đã đóng'), ('pending', 'Chờ xử lý')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='social_messages.channel')),
            ],
            options={
                'verbose_name': 'Hội thoại',
                'verbose_name_plural': 'Hội thoại',
                'db_table': 'conversations',
                'unique_together': {('channel', 'customer_id')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_message_id', models.CharField(max_length=255, unique=True)),
                ('sender_id', models.CharField(max_length=255)),
                ('sender_type', models.CharField(choices=[('customer', 'Khách hàng'), ('page', 'Page/OA'), ('system', 'Hệ thống')], max_length=20)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('audio', 'Audio'), ('video', 'Video'), ('other', 'Other')], default='text', max_length=20)),
                ('content', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField()),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='social_messages.conversation')),
            ],
            options={
                'verbose_name': 'Tin nhắn',
                'verbose_name_plural': 'Tin nhắn',
                'db_table': 'messages',
                'ordering': ['-sent_at'],
            },
        ),
    ]
