# Generated by Django 4.2.16 on 2026-04-14 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_messages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Đang chờ'), ('processed', 'Đã xử lý'), ('failed', 'Thất bại')], default='pending', max_length=20)),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('sentiment', models.CharField(blank=True, max_length=50, null=True)),
                ('priority', models.CharField(blank=True, max_length=50, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='social_messages.message')),
            ],
            options={
                'verbose_name': 'Phân tích tin nhắn',
                'verbose_name_plural': 'Phân tích tin nhắn',
                'db_table': 'message_analyses',
            },
        ),
    ]
