# Generated by Django 4.2.16 on 2026-04-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_messages', '0002_messageanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Báo cáo ngày'), ('custom', 'Báo cáo tùy chọn')], default='daily', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('from_time', models.DateTimeField()),
                ('to_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Đang chờ'), ('processing', 'Đang xử lý'), ('completed', 'Hoàn tất'), ('failed', 'Thất bại')], default='pending', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Báo cáo',
                'verbose_name_plural': 'Báo cáo',
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
