# Generated by Django 4.2.16 on 2026-04-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_messages', '0003_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='current_intent',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='conversation',
            name='current_state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='conversation',
            name='form_retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_bot_prompt',
            field=models.TextField(blank=True, default=''),
        ),
    ]
