# Generated by Django 4.2.16 on 2026-04-20 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_messages', '0004_conversation_current_intent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(choices=[('complaint', 'Khiếu nại'), ('crime_report', 'Tin báo tội phạm'), ('admin_procedure', 'Hỏi thủ tục hành chính')], max_length=50)),
                ('citizen_name', models.CharField(blank=True, default='', max_length=255)),
                ('phone_number', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.TextField(blank=True, default='')),
                ('content', models.TextField()),
                ('event_time', models.CharField(blank=True, default='', max_length=255)),
                ('event_location', models.TextField(blank=True, default='')),
                ('related_person', models.TextField(blank=True, default='')),
                ('urgency_level', models.CharField(blank=True, default='', max_length=50)),
                ('raw_extracted_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('received', 'Đã tiếp nhận'), ('validated', 'Hợp lệ'), ('analyzed', 'Đã phân tích'), ('responded', 'Đã phản hồi'), ('rejected', 'Không hợp lệ')], default='received', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_submissions', to='social_messages.conversation')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_submissions', to='social_messages.message')),
            ],
        ),
    ]
