# Generated by Django 4.2.16 on 2026-04-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_messages', '0005_intakesubmission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intakesubmission',
            options={'ordering': ['-created_at'], 'verbose_name': 'Hồ sơ tiếp nhận', 'verbose_name_plural': 'Hồ sơ tiếp nhận'},
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='priority',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='response_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='sentiment',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='topic',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='current_intent',
            field=models.CharField(blank=True, choices=[('', 'Chưa xác định'), ('complaint', 'Khiếu nại'), ('crime_report', 'Tin báo tội phạm'), ('admin_procedure', 'Hỏi thủ tục hành chính')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='current_state',
            field=models.CharField(blank=True, choices=[('', 'Chưa khởi tạo'), ('awaiting_category_selection', 'Chờ chọn nhóm yêu cầu'), ('awaiting_complaint_form', 'Chờ mẫu khiếu nại'), ('awaiting_crime_report_form', 'Chờ mẫu tin báo tội phạm'), ('awaiting_admin_procedure_form', 'Chờ mẫu hỏi thủ tục hành chính'), ('completed', 'Đã hoàn tất intake')], default='', max_length=100),
        ),
        migrations.AlterModelTable(
            name='intakesubmission',
            table='intake_submissions',
        ),
    ]
