# Generated by Django 4.2.16 on 2026-04-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_messages', '0006_alter_intakesubmission_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='current_state',
            field=models.CharField(blank=True, choices=[('', 'Chưa khởi tạo'), ('awaiting_category_selection', 'Chờ chọn nhóm yêu cầu'), ('awaiting_form', 'Chờ người dân nhập mẫu')], default='', max_length=100),
        ),
    ]
