# Generated by Django 4.2.16 on 2026-04-28 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_messages', '0007_alter_conversation_current_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='access_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='token_last_refreshed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_type',
            field=models.CharField(choices=[('customer', 'Khách hàng'), ('page', 'Page/OA'), ('system', 'Hệ thống'), ('admin', 'Quản trị viên')], max_length=20),
        ),
    ]
