# Generated by Django 4.2.16 on 2026-04-29 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_messages', '0008_channel_access_token_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'verbose_name': 'Kênh tiếp nhận', 'verbose_name_plural': 'Kênh tiếp nhận'},
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'verbose_name': 'Cuộc hội thoại', 'verbose_name_plural': 'Cuộc hội thoại'},
        ),
        migrations.AlterModelOptions(
            name='intakesubmission',
            options={'ordering': ['-created_at'], 'verbose_name': 'Hồ sơ phản ánh', 'verbose_name_plural': 'Hồ sơ phản ánh'},
        ),
        migrations.AlterModelOptions(
            name='messageanalysis',
            options={'verbose_name': 'Phân tích AI', 'verbose_name_plural': 'Phân tích AI'},
        ),
        migrations.AlterField(
            model_name='channel',
            name='access_token',
            field=models.TextField(blank=True, null=True, verbose_name='Access Token'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='access_token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hết hạn token'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='external_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='ID ngoài hệ thống'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên kênh'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='platform',
            field=models.CharField(choices=[('zalo', 'Zalo OA'), ('facebook', 'Facebook Messenger')], max_length=20, verbose_name='Nền tảng'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='refresh_token',
            field=models.TextField(blank=True, null=True, verbose_name='Refresh Token'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='token_last_refreshed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Lần refresh gần nhất'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='webhook_secret',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Webhook Secret'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='social_messages.channel', verbose_name='Kênh'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='current_intent',
            field=models.CharField(blank=True, choices=[('', 'Chưa xác định'), ('complaint', 'Khiếu nại'), ('crime_report', 'Tin báo tội phạm'), ('admin_procedure', 'Thủ tục hành chính')], default='', max_length=50, verbose_name='Loại yêu cầu'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='current_state',
            field=models.CharField(blank=True, choices=[('', 'Chưa khởi tạo'), ('awaiting_category_selection', 'Chờ chọn nhóm yêu cầu'), ('awaiting_form', 'Chờ nhập thông tin')], default='', max_length=100, verbose_name='Trạng thái luồng'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='customer_id',
            field=models.CharField(max_length=255, verbose_name='ID khách hàng'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên khách hàng'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='form_retry_count',
            field=models.IntegerField(default=0, verbose_name='Số lần nhập lại form'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='last_bot_prompt',
            field=models.TextField(blank=True, default='', verbose_name='Câu hỏi gần nhất của bot'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='last_message_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tin nhắn cuối'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('open', 'Đang mở'), ('closed', 'Đã đóng'), ('pending', 'Chờ xử lý')], default='open', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối'),
        ),
        migrations.AlterField(
            model_name='intakesubmission',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='intakesubmission',
            name='citizen_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Tên người dân'),
        ),
        migrations.AlterField(
            model_name='intakesubmission',
            name='content',
            field=models.TextField(verbose_name='Nội dung phản ánh'),
        ),
        migrations.AlterField(
            model_name='intakesubmission',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_submissions', to='social_messages.conversation', verbose_name='Cuộc hội thoại'),
        ),
        migrations.AlterField(
            model_name='intakesubmission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='intakesubmission',
            name='event_location',
            field=models.TextField(blank=True, default='', verbose_name='Địa điểm'),
        ),
        migrations.AlterField(
            model_name='intakesubmission',
            name='event_time',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Thời gian xảy ra'),
        ),
        migrations.AlterField(
            model_name='intakesubmission',
            name='intent',
            field=models.CharField(choices=[('complaint', 'Khiếu nại'), ('crime_report', 'Tin báo tội phạm'), ('admin_procedure', 'Thủ tục hành chính')], max_length=50, verbose_name='Loại phản ánh'),
        ),
        migrations.AlterField(
            model_name='intakesubmission',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_submissions', to='social_messages.message', verbose_name='Tin nhắn nguồn'),
        ),
        migrations.AlterField(
            model_name='intakesubmission',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='intakesubmission',
            name='priority',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Độ ưu tiên'),
        ),
        migrations.AlterField(
            model_name='intakesubmission',
            name='raw_extracted_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Dữ liệu AI trích xuất'),
        ),
        migrations.AlterField(
            model_name='intakesubmission',
            name='related_person',
            field=models.TextField(blank=True, default='', verbose_name='Người liên quan'),
        ),
        migrations.AlterField(
            model_name='intakesubmission',
            name='response_text',
            field=models.TextField(blank=True, default='', verbose_name='Phản hồi'),
        ),
        migrations.AlterField(
            model_name='intakesubmission',
            name='sentiment',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Cảm xúc'),
        ),
        migrations.AlterField(
            model_name='intakesubmission',
            name='status',
            field=models.CharField(choices=[('received', 'Đã tiếp nhận'), ('validated', 'Hợp lệ'), ('analyzed', 'Đã phân tích'), ('responded', 'Đã phản hồi'), ('rejected', 'Không hợp lệ')], default='received', max_length=50, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='intakesubmission',
            name='summary',
            field=models.TextField(blank=True, default='', verbose_name='Tóm tắt'),
        ),
        migrations.AlterField(
            model_name='intakesubmission',
            name='topic',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Chủ đề'),
        ),
        migrations.AlterField(
            model_name='intakesubmission',
            name='urgency_level',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Mức độ khẩn cấp'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='social_messages.conversation', verbose_name='Cuộc hội thoại'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Văn bản'), ('image', 'Hình ảnh'), ('file', 'Tệp'), ('audio', 'Âm thanh'), ('video', 'Video'), ('other', 'Khác')], default='text', max_length=20, verbose_name='Loại tin nhắn'),
        ),
        migrations.AlterField(
            model_name='message',
            name='platform_message_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='ID tin nhắn nền tảng'),
        ),
        migrations.AlterField(
            model_name='message',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Dữ liệu thô'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_id',
            field=models.CharField(max_length=255, verbose_name='ID người gửi'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_type',
            field=models.CharField(choices=[('customer', 'Khách hàng'), ('page', 'Page/OA'), ('system', 'Hệ thống'), ('admin', 'Quản trị viên')], max_length=20, verbose_name='Loại người gửi'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_at',
            field=models.DateTimeField(verbose_name='Thời gian gửi'),
        ),
        migrations.AlterField(
            model_name='messageanalysis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='messageanalysis',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Lỗi'),
        ),
        migrations.AlterField(
            model_name='messageanalysis',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='social_messages.message', verbose_name='Tin nhắn'),
        ),
        migrations.AlterField(
            model_name='messageanalysis',
            name='priority',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Độ ưu tiên'),
        ),
        migrations.AlterField(
            model_name='messageanalysis',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian xử lý'),
        ),
        migrations.AlterField(
            model_name='messageanalysis',
            name='result_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Kết quả AI'),
        ),
        migrations.AlterField(
            model_name='messageanalysis',
            name='sentiment',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cảm xúc'),
        ),
        migrations.AlterField(
            model_name='messageanalysis',
            name='status',
            field=models.CharField(choices=[('pending', 'Đang chờ'), ('processed', 'Đã xử lý'), ('failed', 'Thất bại')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='messageanalysis',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='Tóm tắt'),
        ),
        migrations.AlterField(
            model_name='messageanalysis',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Chủ đề'),
        ),
        migrations.AlterField(
            model_name='report',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hoàn thành lúc'),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='report',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên file'),
        ),
        migrations.AlterField(
            model_name='report',
            name='file_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Đường dẫn file'),
        ),
        migrations.AlterField(
            model_name='report',
            name='from_time',
            field=models.DateTimeField(verbose_name='Từ thời gian'),
        ),
        migrations.AlterField(
            model_name='report',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('daily', 'Báo cáo ngày'), ('custom', 'Báo cáo tùy chọn')], default='daily', max_length=20, verbose_name='Loại báo cáo'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Đang chờ'), ('processing', 'Đang xử lý'), ('completed', 'Hoàn tất'), ('failed', 'Thất bại')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='report',
            name='to_time',
            field=models.DateTimeField(verbose_name='Đến thời gian'),
        ),
    ]
