# Generated by Django 4.2.16 on 2026-05-05 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_messages', '0009_alter_channel_options_alter_conversation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True, verbose_name='Mã lệnh')),
                ('name', models.CharField(max_length=255, verbose_name='Tên lệnh')),
                ('action', models.CharField(choices=[('today_insight', 'Tổng quan hôm nay'), ('system_status', 'Trạng thái hệ thống'), ('generate_report', 'Tạo báo cáo'), ('static_reply', 'Trả lời cố định')], max_length=50, verbose_name='Hành động')),
                ('report_period', models.CharField(choices=[('none', 'Không áp dụng'), ('today', 'Hôm nay'), ('yesterday', 'Hôm qua'), ('current_week', 'Tuần này'), ('current_month', 'Tháng này'), ('specific_date', 'Ngày cụ thể từ regex')], default='none', max_length=30, verbose_name='Kỳ báo cáo')),
                ('report_type', models.CharField(blank=True, default='', max_length=20, verbose_name='Loại báo cáo')),
                ('report_title_template', models.CharField(blank=True, default='', max_length=255, verbose_name='Mẫu tiêu đề báo cáo')),
                ('static_reply_text', models.TextField(blank=True, default='', verbose_name='Nội dung trả lời cố định')),
                ('help_text', models.CharField(blank=True, default='', max_length=255, verbose_name='Gợi ý hiển thị')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
            ],
            options={
                'verbose_name': 'Lệnh quản trị',
                'verbose_name_plural': 'Lệnh quản trị',
                'db_table': 'admin_commands',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IntakeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True, verbose_name='Mã nhóm')),
                ('name', models.CharField(max_length=255, verbose_name='Tên nhóm')),
                ('selection_value', models.CharField(max_length=20, unique=True, verbose_name='Giá trị người dân chọn')),
                ('aliases', models.JSONField(blank=True, default=list, verbose_name='Từ khóa lựa chọn khác')),
                ('description', models.TextField(blank=True, default='', verbose_name='Mô tả')),
                ('menu_order', models.PositiveIntegerField(default=1, verbose_name='Thứ tự hiển thị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('default_topic', models.CharField(blank=True, default='', max_length=255, verbose_name='Chủ đề mặc định')),
                ('default_sentiment', models.CharField(blank=True, default='trung lập', max_length=50, verbose_name='Cảm xúc mặc định')),
                ('default_priority', models.CharField(blank=True, default='normal', max_length=50, verbose_name='Ưu tiên mặc định')),
                ('default_department', models.CharField(blank=True, default='', max_length=255, verbose_name='Bộ phận gợi ý')),
                ('requires_human_review', models.BooleanField(default=True, verbose_name='Cần người rà soát')),
                ('success_reply_text', models.TextField(blank=True, default='', verbose_name='Phản hồi sau khi tiếp nhận')),
                ('urgent_reply_text', models.TextField(blank=True, default='', verbose_name='Phản hồi khi khẩn cấp')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
            ],
            options={
                'verbose_name': 'Nhóm tiếp nhận',
                'verbose_name_plural': 'Nhóm tiếp nhận',
                'db_table': 'intake_categories',
                'ordering': ['menu_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IntakeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề mẫu')),
                ('intro_text', models.TextField(blank=True, default='', verbose_name='Mở đầu')),
                ('footer_text', models.TextField(blank=True, default='', verbose_name='Kết thúc/hướng dẫn')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='social_messages.intakecategory', verbose_name='Nhóm tiếp nhận')),
            ],
            options={
                'verbose_name': 'Mẫu tiếp nhận',
                'verbose_name_plural': 'Mẫu tiếp nhận',
                'db_table': 'intake_templates',
                'ordering': ['category__menu_order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='conversation',
            name='current_intent',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Mã nhóm cũ/tương thích'),
        ),
        migrations.AlterField(
            model_name='intakesubmission',
            name='intent',
            field=models.CharField(max_length=80, verbose_name='Mã nhóm cũ/tương thích'),
        ),
        migrations.AlterField(
            model_name='intakesubmission',
            name='raw_extracted_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Dữ liệu trích xuất'),
        ),
        migrations.CreateModel(
            name='KeywordRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên luật keyword')),
                ('match_type', models.CharField(choices=[('any_keyword', 'Khớp một từ khóa bất kỳ'), ('all_keywords', 'Khớp tất cả từ khóa'), ('regex', 'Khớp regex'), ('always', 'Luôn khớp')], default='any_keyword', max_length=50, verbose_name='Kiểu khớp')),
                ('keywords', models.JSONField(blank=True, default=list, verbose_name='Danh sách từ khóa')),
                ('pattern', models.TextField(blank=True, default='', verbose_name='Regex nếu dùng')),
                ('topic', models.CharField(blank=True, default='', max_length=255, verbose_name='Chủ đề')),
                ('sentiment', models.CharField(blank=True, default='trung lập', max_length=50, verbose_name='Cảm xúc')),
                ('priority', models.CharField(blank=True, default='normal', max_length=50, verbose_name='Độ ưu tiên')),
                ('summary_template', models.TextField(blank=True, default='{content}', verbose_name='Mẫu tóm tắt')),
                ('response_template', models.TextField(blank=True, default='', verbose_name='Mẫu phản hồi')),
                ('result_payload', models.JSONField(blank=True, default=dict, verbose_name='Payload bổ sung')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('category', models.ForeignKey(blank=True, help_text='Để trống nếu áp dụng toàn hệ thống', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keyword_rules', to='social_messages.intakecategory', verbose_name='Nhóm tiếp nhận')),
            ],
            options={
                'verbose_name': 'Luật keyword',
                'verbose_name_plural': 'Luật keyword',
                'db_table': 'keyword_rules',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IntakeValidationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên luật')),
                ('rule_type', models.CharField(choices=[('min_length', 'Độ dài tối thiểu'), ('blocked_keywords', 'Từ khóa bị chặn'), ('regex', 'Kiểm tra regex'), ('required_any', 'Bắt buộc một trong nhiều trường')], max_length=50, verbose_name='Loại luật')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Cấu hình luật')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Thông báo lỗi')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('category', models.ForeignKey(blank=True, help_text='Để trống nếu áp dụng toàn hệ thống', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validation_rules', to='social_messages.intakecategory', verbose_name='Nhóm tiếp nhận')),
            ],
            options={
                'verbose_name': 'Luật kiểm tra form',
                'verbose_name_plural': 'Luật kiểm tra form',
                'db_table': 'intake_validation_rules',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AdminCommandPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_text', models.TextField(verbose_name='Mẫu câu')),
                ('match_type', models.CharField(choices=[('exact', 'Khớp chính xác'), ('contains', 'Có chứa cụm từ'), ('regex', 'Regex')], default='contains', max_length=20, verbose_name='Kiểu khớp')),
                ('priority', models.PositiveIntegerField(default=100, verbose_name='Độ ưu tiên')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='social_messages.admincommand', verbose_name='Lệnh quản trị')),
            ],
            options={
                'verbose_name': 'Mẫu câu lệnh quản trị',
                'verbose_name_plural': 'Mẫu câu lệnh quản trị',
                'db_table': 'admin_command_patterns',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='current_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_conversations', to='social_messages.intakecategory', verbose_name='Nhóm tiếp nhận hiện tại'),
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='social_messages.intakecategory', verbose_name='Nhóm tiếp nhận'),
        ),
        migrations.CreateModel(
            name='IntakeTemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.SlugField(max_length=80, verbose_name='Mã trường')),
                ('label', models.CharField(max_length=255, verbose_name='Nhãn hiển thị')),
                ('target_field', models.CharField(choices=[('citizen_name', 'Tên người dân'), ('phone_number', 'Số điện thoại'), ('address', 'Địa chỉ'), ('content', 'Nội dung phản ánh'), ('event_time', 'Thời gian xảy ra'), ('event_location', 'Địa điểm'), ('related_person', 'Người liên quan'), ('urgency_level', 'Mức độ khẩn cấp'), ('extra_data', 'Dữ liệu mở rộng/JSON')], default='extra_data', max_length=50, verbose_name='Ánh xạ vào cột')),
                ('field_type', models.CharField(choices=[('text', 'Văn bản'), ('textarea', 'Nội dung dài'), ('phone', 'Số điện thoại'), ('datetime', 'Thời gian'), ('choice', 'Lựa chọn')], default='text', max_length=20, verbose_name='Kiểu dữ liệu')),
                ('is_required', models.BooleanField(default=True, verbose_name='Bắt buộc')),
                ('aliases', models.JSONField(blank=True, default=list, verbose_name='Tên gọi khác')),
                ('help_text', models.TextField(blank=True, default='', verbose_name='Gợi ý nhập')),
                ('choice_options', models.JSONField(blank=True, default=list, verbose_name='Các lựa chọn')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='social_messages.intaketemplate', verbose_name='Mẫu tiếp nhận')),
            ],
            options={
                'verbose_name': 'Trường trong mẫu tiếp nhận',
                'verbose_name_plural': 'Trường trong mẫu tiếp nhận',
                'db_table': 'intake_template_fields',
                'ordering': ['order', 'id'],
                'unique_together': {('template', 'field_key')},
            },
        ),
    ]
