# Generated by Django 4.2.16 on 2026-07-10 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_messages', '0010_admincommand_intakecategory_intaketemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='state_entered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm chuyển trạng thái'),
        ),
    ]
