# Generated by Django 4.2.16 on 2026-07-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_messages', '0011_conversation_state_entered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='intaketemplatefield',
            name='match_condition',
            field=models.CharField(choices=[('==', 'Chính xác (==)'), ('like', 'Chứa từ khóa (like)')], default='==', max_length=10, verbose_name='Điều kiện so sánh'),
        ),
    ]
