# Generated by Django 4.2.16 on 2026-07-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_messages', '0012_intaketemplatefield_match_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(choices=[('zalo_webhook', 'Zalo Webhook'), ('facebook_webhook', 'Facebook Webhook'), ('zalo_api', 'Zalo API'), ('facebook_api', 'Facebook API'), ('gemini_api', 'Gemini API'), ('system', 'Hệ thống')], max_length=50, verbose_name='Hệ thống')),
                ('direction', models.CharField(choices=[('inbound', 'Gọi vào (Inbound)'), ('outbound', 'Gọi ra (Outbound)')], max_length=20, verbose_name='Chiều gọi')),
                ('endpoint', models.CharField(blank=True, default='', max_length=500, verbose_name='Endpoint/URL')),
                ('method', models.CharField(blank=True, default='POST', max_length=20, verbose_name='Phương thức')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='Mã HTTP')),
                ('request_payload', models.JSONField(blank=True, null=True, verbose_name='Payload gửi đi/nhận vào')),
                ('response_payload', models.JSONField(blank=True, null=True, verbose_name='Payload trả về')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Thông báo lỗi')),
                ('processing_time_ms', models.FloatField(blank=True, null=True, verbose_name='Thời gian xử lý (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
            ],
            options={
                'verbose_name': 'Lịch sử API (Integration Log)',
                'verbose_name_plural': 'Lịch sử API (Integration Logs)',
                'db_table': 'integration_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
