# Generated by Django 4.2.16 on 2026-07-13 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_messages', '0013_integrationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakesubmission',
            name='processing_status',
            field=models.CharField(choices=[('unassigned', 'Chưa phân công'), ('pending', 'Chưa xử lý'), ('in_progress', 'Đang xử lý'), ('completed', 'Đã xử lý'), ('returned', 'Trả lại')], default='unassigned', max_length=20, verbose_name='Trạng thái xử lý'),
        ),
        migrations.AlterField(
            model_name='intakesubmission',
            name='status',
            field=models.CharField(choices=[('received', 'Đã tiếp nhận'), ('validated', 'Hợp lệ'), ('analyzed', 'Đã phân tích'), ('responded', 'Đã phản hồi'), ('rejected', 'Không hợp lệ')], default='received', max_length=50, verbose_name='Trạng thái hệ thống'),
        ),
        migrations.CreateModel(
            name='IntakeSubmissionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('main', 'Xử lý chính'), ('co_handler', 'Phối hợp')], default='co_handler', max_length=20, verbose_name='Vai trò')),
                ('status', models.CharField(choices=[('pending', 'Chưa xử lý'), ('in_progress', 'Đang xử lý'), ('completed', 'Đã xử lý'), ('returned', 'Trả lại')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('return_reason', models.TextField(blank=True, default='', verbose_name='Lý do trả lại')),
                ('processing_note', models.TextField(blank=True, default='', verbose_name='Thông tin xử lý')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày phân công')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='social_messages.intakesubmission', verbose_name='Hồ sơ tiếp nhận')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Người xử lý')),
            ],
            options={
                'verbose_name': 'Phân công xử lý',
                'verbose_name_plural': 'Phân công xử lý',
                'db_table': 'intake_submission_assignments',
                'unique_together': {('submission', 'user')},
            },
        ),
    ]
