# Generated by Django 4.2.16 on 2026-07-13 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_messages', '0014_intakesubmission_processing_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='intakesubmissionassignment',
            unique_together=set(),
        ),
    ]
