# Generated by Django 4.2.16 on 2026-07-13 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_messages', '0015_alter_intakesubmissionassignment_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeSubmissionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('assign', 'Phân công xử lý'), ('accept', 'Tiếp nhận hồ sơ'), ('return', 'Trả lại hồ sơ'), ('complete', 'Hoàn thành xử lý')], max_length=20, verbose_name='Hành động')),
                ('note', models.TextField(blank=True, default='', verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='social_messages.intakesubmission', verbose_name='Hồ sơ tiếp nhận')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_history', to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
            ],
            options={
                'verbose_name': 'Lịch sử xử lý',
                'verbose_name_plural': 'Lịch sử xử lý',
                'db_table': 'intake_submission_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
