# Generated by Django 4.2.16 on 2026-07-14 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_messages', '0017_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=255, unique=True, verbose_name='ID khách hàng')),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên khách hàng')),
                ('reason', models.TextField(blank=True, default='', verbose_name='Lý do chặn')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang chặn')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày chặn')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
            ],
            options={
                'verbose_name': 'Danh sách chặn',
                'verbose_name_plural': 'Danh sách chặn',
                'db_table': 'customer_blacklist',
                'ordering': ['-created_at'],
            },
        ),
    ]
