# Generated by Django 4.2.16 on 2026-07-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_messages', '0018_customerblacklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Mã cấu hình')),
                ('value', models.TextField(blank=True, default='', verbose_name='Giá trị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Bật/Tắt')),
                ('description', models.TextField(blank=True, default='', verbose_name='Mô tả')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
            ],
            options={
                'verbose_name': 'Cấu hình hệ thống',
                'verbose_name_plural': 'Cấu hình hệ thống',
                'db_table': 'system_configs',
            },
        ),
    ]
