# Generated by Django 4.2.16 on 2026-07-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_messages', '0019_systemconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachments',
            field=models.JSONField(blank=True, default=list, verbose_name='Đính kèm'),
        ),
    ]
