# Generated by Django 4.2.16 on 2026-09-03 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_messages', '0020_message_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admincommand',
            name='action',
            field=models.CharField(choices=[('today_insight', 'Tổng quan hôm nay'), ('system_status', 'Trạng thái hệ thống'), ('generate_report', 'Tạo báo cáo'), ('static_reply', 'Trả lời cố định'), ('list_submissions', 'Danh sách hồ sơ'), ('submission_detail', 'Xem chi tiết hồ sơ')], max_length=50, verbose_name='Hành động'),
        ),
    ]
