# Generated by data migration

from django.db import migrations


def seed_submission_commands(apps, schema_editor):
    AdminCommand = apps.get_model("social_messages", "AdminCommand")
    AdminCommandPattern = apps.get_model("social_messages", "AdminCommandPattern")

    # 1. Lệnh xem danh sách hồ sơ
    cmd_list, _ = AdminCommand.objects.update_or_create(
        code="list_submissions",
        defaults={
            "name": "Xem danh sách hồ sơ",
            "action": "list_submissions",
            "help_text": "danh sách hồ sơ",
            "order": 8,
            "is_active": True,
        }
    )

    list_patterns = [
        ("contains", "danh sách hồ sơ", 10),
        ("contains", "danh sach ho so", 11),
        ("contains", "hồ sơ của tôi", 12),
        ("contains", "ho so cua toi", 13),
        ("contains", "các hồ sơ", 14),
        ("contains", "cac ho so", 15),
        ("exact", "ds hồ sơ", 16),
        ("exact", "ds ho so", 17),
        ("exact", "dshs", 18),
        ("exact", "hồ sơ", 19),
        ("exact", "ho so", 20),
        ("contains", "hồ sơ chưa phân công", 21),
        ("contains", "ho so chua phan cong", 22),
        ("contains", "chưa phân công", 23),
        ("contains", "chua phan cong", 24),
        ("contains", "hồ sơ chưa xử lý", 25),
        ("contains", "ho so chua xu ly", 26),
        ("contains", "chưa xử lý", 27),
        ("contains", "chua xu ly", 28),
        ("contains", "hồ sơ đang xử lý", 29),
        ("contains", "ho so dang xu ly", 30),
        ("contains", "đang xử lý", 31),
        ("contains", "dang xu ly", 32),
        ("contains", "hồ sơ hôm nay", 33),
        ("contains", "ho so hom nay", 34),
        ("contains", "hồ sơ hôm qua", 35),
        ("contains", "ho so hom qua", 36),
        ("contains", "hồ sơ khẩn cấp", 37),
        ("contains", "ho so khan cap", 38),
        ("contains", "hồ sơ ưu tiên", 39),
        ("contains", "ho so uu tien", 40),
        ("regex", r"^(?:xem\s+)?(?:danh\s*sách\s+|danh\s*sach\s+)?(?:hồ\s*sơ|ho\s*so|hs)\s+ngày\s+(?P<day>\d{1,2})[/-](?P<month>\d{1,2})[/-](?P<year>\d{4})$", 41),
        ("regex", r"^(?:xem\s+)?(?:danh\s*sách\s+|danh\s*sach\s+)?(?:hồ\s*sơ|ho\s*so|hs)\s+ngay\s+(?P<day>\d{1,2})[/-](?P<month>\d{1,2})[/-](?P<year>\d{4})$", 42),
    ]
    for match_type, pattern_text, priority in list_patterns:
        AdminCommandPattern.objects.update_or_create(
            command=cmd_list,
            pattern_text=pattern_text,
            defaults={
                "match_type": match_type,
                "priority": priority,
                "is_active": True,
            }
        )

    # 2. Lệnh xem chi tiết hồ sơ
    cmd_detail, _ = AdminCommand.objects.update_or_create(
        code="submission_detail",
        defaults={
            "name": "Xem chi tiết hồ sơ theo ID",
            "action": "submission_detail",
            "help_text": "xem hồ sơ 114",
            "order": 9,
            "is_active": True,
        }
    )

    detail_patterns = [
        ("regex", r"^(?:xem\s+)?(?:hồ\s*sơ|ho\s*so|chi\s*tiết\s*hồ\s*sơ|chi\s*tiet\s*ho\s*so|hs)\s*#?(?P<submission_id>\d+)$", 5),
    ]
    for match_type, pattern_text, priority in detail_patterns:
        AdminCommandPattern.objects.update_or_create(
            command=cmd_detail,
            pattern_text=pattern_text,
            defaults={
                "match_type": match_type,
                "priority": priority,
                "is_active": True,
            }
        )


def reverse_seed_submission_commands(apps, schema_editor):
    AdminCommand = apps.get_model("social_messages", "AdminCommand")
    AdminCommand.objects.filter(code__in=["list_submissions", "submission_detail"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('social_messages', '0021_alter_admincommand_action'),
    ]

    operations = [
        migrations.RunPython(seed_submission_commands, reverse_seed_submission_commands),
    ]
