"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from pathlib import Path
import os
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR.parent / "env" / ".env")

SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-fallback-key")
DEBUG = os.getenv("DJANGO_DEBUG", "False") == "True"

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "*").split(",")

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "social_messages",
    "webhooks",
    "django_recaptcha",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB", "social_ai_db"),
        "USER": os.getenv("POSTGRES_USER", "social_ai_user"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", "social_ai_password"),
        "HOST": os.getenv("POSTGRES_HOST", "db"),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

LANGUAGE_CODE = os.getenv("LANGUAGE_CODE", "vi")
TIME_ZONE = os.getenv("TIME_ZONE", "Asia/Ho_Chi_Minh")
USE_I18N = True
USE_TZ = True

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

#media files (user uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

#Celery Configuration
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://redis:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://redis:6379/0")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = os.getenv("TIME_ZONE", "Asia/Ho_Chi_Minh")

# ZALO admin sender IDs configuration has been moved to database-driven user profiles (UserProfile.zalo_id)
FACEBOOK_VERIFY_TOKEN = os.getenv("FACEBOOK_VERIFY_TOKEN", "")
ZALO_WEBHOOK_SECRET = os.getenv("ZALO_WEBHOOK_SECRET", "")

ZALO_APP_ID = os.getenv("ZALO_APP_ID", "")
ZALO_APP_SECRET = os.getenv("ZALO_APP_SECRET", "")

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
CSRF_TRUSTED_ORIGINS = [
    "https://webhook.socialai.id.vn",
]



PUBLIC_BASE_URL = os.getenv("PUBLIC_BASE_URL", "")
DAILY_REPORT_BANNER_URL = os.getenv("DAILY_REPORT_BANNER_URL", "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=800&auto=format&fit=crop")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",  # 👈 Quan trọng
    },
}

# ReCAPTCHA V3 Settings
RECAPTCHA_PUBLIC_KEY = os.getenv("RECAPTCHA_PUBLIC_KEY", "dummy-public-key")
RECAPTCHA_PRIVATE_KEY = os.getenv("RECAPTCHA_PRIVATE_KEY", "dummy-private-key")
RECAPTCHA_REQUIRED_SCORE = 0.5

# Cấu hình Jazzmin
JAZZMIN_SETTINGS = {
    "site_title": "Social AI Assistant",
    "site_header": "Social AI Assistant",
    "site_brand": "Social AI Admin",
    "welcome_sign": "Trang quản trị hệ thống tiếp nhận phản ánh",
    "copyright": "Social AI Assistant",

    "user_avatar": "avatar",

    "show_sidebar": True,
    "navigation_expanded": True,
    "custom_css": "css/custom.css",

    "topmenu_links": [
    {"name": "Trang chủ", "url": "admin:index", "permissions": ["auth.view_user"]},
    {"name": "Dashboard", "url": "/social-messages/admin-dashboard/", "permissions": ["auth.view_user"]},
    {"name": "Tin nhắn", "url": "/admin/social_messages/message/"},
    {"name": "Phản ánh", "url": "/admin/social_messages/intakesubmission/"},
    {"name": "Báo cáo", "url": "/admin/social_messages/report/"},
    {"name": "Xem website", "url": "/", "new_window": True},
    ],

    "order_with_respect_to": [
        "social_messages.Channel",
        "social_messages.Conversation",
        "social_messages.Message",
        "social_messages.IntakeSubmission",
        "social_messages.Report",
        "auth.User",
        "auth.Group",
    ],

    "icons": {
    "social_messages.Channel": "fas fa-satellite-dish",
    "social_messages.Conversation": "fas fa-comments",
    "social_messages.Message": "fas fa-comment-dots",
    "social_messages.IntakeSubmission": "fas fa-folder-open",
    "social_messages.Report": "fas fa-file-excel",
    "social_messages.IntakeCategory": "fas fa-layer-group",
    "social_messages.IntakeTemplate": "fas fa-file-alt",
    "social_messages.IntakeTemplateField": "fas fa-list-ul",
    "social_messages.IntakeValidationRule": "fas fa-clipboard-check",
    "social_messages.KeywordRule": "fas fa-key",
    "social_messages.AdminCommand": "fas fa-terminal",
    "social_messages.AdminCommandPattern": "fas fa-keyboard",

    "auth.User": "fas fa-user-shield",
    "auth.Group": "fas fa-users-cog",
    },

    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",

    "changeform_format": "horizontal_tabs",
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-success",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-success",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "darkly",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}


from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    "refresh-zalo-tokens-every-30-minutes": {
        "task": "social_messages.tasks.refresh_all_zalo_tokens_if_needed",
        "schedule": 1800.0,
    },
    "cleanup-integration-logs-daily": {
        "task": "social_messages.tasks.cleanup_integration_logs",
        "schedule": 86400.0,
    },
    "send-daily-24h-summary": {
        "task": "social_messages.tasks.send_daily_24h_summary_report",
        "schedule": crontab(hour=8, minute=0),
    },
}

# Thời gian hết hạn của session tính bằng giây (Ví dụ ở đây là 3600 giây = 1 giờ)
SESSION_COOKIE_AGE = 3600

# (Tùy chọn) Nếu bạn muốn session tự động bị hủy ngay khi người dùng đóng trình duyệt:
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
